// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace nArchitectureExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "nArchitectureExtension.b451418e-cf7f-406a-bbf2-e8caa0f513e2";
        public const string Name = "nArchitectureExtension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "serdar";
        public const string Tags = "";
    }
}
