// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace nArchitectureExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string nArchitectureExtensionString = "d2514a69-880b-41e3-9c48-4c0ca5c7e609";
        public static Guid nArchitectureExtension = new Guid(nArchitectureExtensionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int GenerateCodeFromEntityCommand = 0x0200;
    }
}